"""FastAPI application assembly, background worker lifecycle, and API mounting."""

import asyncio
import os
from collections.abc import AsyncIterator, Mapping
from contextlib import asynccontextmanager, suppress
from pathlib import Path
from typing import Any

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, async_sessionmaker

from app.api import auth, comics, exports, imports, tags
from app.auth import LoginRateLimiter, cleanup_expired_sessions
from app.config import Settings, get_settings
from app.covers import CoverStore
from app.database import ComicRepository, create_database_engine, create_session_factory, initialize_database
from app.jm_client import AsyncJmComicClient, ComicMetadata, ComicUpstream
from app.models import Comic
from app.tagging import tag_preferences_from_settings
from app.tasks import ComicTaskQueue


class SessionComicRepository:
    """Give background workers fresh short-lived sessions for each persistence action."""

    def __init__(self, session_factory: async_sessionmaker[AsyncSession]) -> None:
        """Store the factory used to create isolated worker database sessions."""
        self._session_factory = session_factory

    @asynccontextmanager
    async def _repository(self) -> AsyncIterator[ComicRepository]:
        """Yield one core repository and guarantee its session is closed afterwards."""
        async with self._session_factory() as session:
            yield ComicRepository(session)

    async def get_comic(self, comic_id: int) -> Any | None:
        """Load a comic for worker processing through an isolated repository."""
        async with self._repository() as repository:
            return await repository.get_comic(comic_id)

    async def set_status(self, comic_id: int, status: str, error: str | None = None) -> None:
        """Persist the lifecycle status generated by one background work item."""
        async with self._repository() as repository:
            await repository.set_status(comic_id, status, error)

    async def save_metadata(self, comic_id: int, metadata: ComicMetadata | Mapping[str, object]) -> None:
        """Persist a successful metadata snapshot through an isolated repository."""
        async with self._repository() as repository:
            await repository.save_metadata(comic_id, metadata)

    async def bump_cover_version(self, comic_id: int) -> None:
        """Advance a comic's persisted cover cache-busting version."""
        async with self._repository() as repository:
            await repository.bump_cover_version(comic_id)

    async def list_unfinished_ids(self) -> list[int]:
        """Return IDs that should resume background work after a restart."""
        async with self._repository() as repository:
            return await repository.list_unfinished_ids()

    async def list_comic_ids(self) -> list[int]:
        """Return all currently persisted IDs for orphan-cover maintenance."""
        async with self._session_factory() as session:
            return list((await session.scalars(select(Comic.id))).all())


async def _periodic_orphan_cleanup(covers: CoverStore, repository: SessionComicRepository) -> None:
    """Remove covers whose comics disappeared once per day until cancelled."""
    while True:
        await asyncio.sleep(86_400)
        await covers.cleanup_orphans(await repository.list_comic_ids())


def _cover_directory() -> Path:
    """Return the configurable data directory used to persist WebP cover files."""
    return Path(os.getenv("COVERS_DIR", "/data/covers"))


def create_app(
    *,
    settings: Settings | None = None,
    upstream: ComicUpstream | None = None,
    cover_store: CoverStore | None = None,
) -> FastAPI:
    """Build an injectable FastAPI application without starting background work yet."""
    configured_settings = settings or get_settings()
    engine = create_database_engine(configured_settings)
    session_factory = create_session_factory(engine)
    repository = SessionComicRepository(session_factory)
    covers = cover_store or CoverStore(_cover_directory())
    queue = ComicTaskQueue(repository, upstream or AsyncJmComicClient(), covers=covers)

    @asynccontextmanager
    async def lifespan(app: FastAPI) -> AsyncIterator[None]:
        """Initialize storage, recover jobs, and reliably release workers on shutdown."""
        cleanup_task: asyncio.Task[None] | None = None
        queue_started = False
        try:
            configured_settings.validate_secrets()
            tag_preferences_from_settings(configured_settings)
            await initialize_database(engine)
            async with session_factory() as session:
                await cleanup_expired_sessions(session)
            await covers.cleanup_orphans(await repository.list_comic_ids())
            await queue.start()
            queue_started = True
            await queue.recover_unfinished()
            cleanup_task = asyncio.create_task(_periodic_orphan_cleanup(covers, repository))
            yield
        finally:
            if cleanup_task is not None:
                cleanup_task.cancel()
                with suppress(asyncio.CancelledError):
                    await cleanup_task
            if queue_started:
                await queue.stop()
            await engine.dispose()

    app = FastAPI(
        title="Favlist",
        version="1.0.0",
        lifespan=lifespan,
        docs_url=None,
        redoc_url=None,
        openapi_url=None,
    )
    app.state.settings = configured_settings
    app.state.engine = engine
    app.state.session_factory = session_factory
    app.state.task_queue = queue
    app.state.cover_store = covers
    app.state.login_rate_limiter = LoginRateLimiter(
        configured_settings.login_rate_limit_attempts,
        configured_settings.login_rate_limit_window_seconds,
    )

    def configured_settings_dependency() -> Settings:
        """Return this application instance's injectable immutable settings."""
        return configured_settings

    app.dependency_overrides[get_settings] = configured_settings_dependency
    app.add_middleware(
        CORSMiddleware,
        allow_origins=list(configured_settings.cors_allowed_origins),
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )
    app.include_router(auth.router, prefix="/api")
    app.include_router(imports.router, prefix="/api")
    app.include_router(comics.router, prefix="/api")
    app.include_router(tags.router, prefix="/api")
    app.include_router(exports.router, prefix="/api")
    return app


app = create_app()
